# fly.toml app configuration file generated for iankx on 2024-11-09T11:10:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iankx'
primary_region = 'jnb'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[experimental]
  auto_rollback = true

[build]

[deploy]
  strategy = 'rolling'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 256
    soft_limit = 255

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'
